name: 'Linter & TypeScript'
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '16'
            - name: Install Dependencies
              run: npm install
            - name: Run ESLint
              run: npm run lint
            - name: Run TypeScript compiler
              run: npm run typecheck
