name: "Linter & TypeScript"
on: push
jobs:
  linter-and-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Generate OpenAPI client
        run: npm run generate-api
      - name: Run ESLint
        run: npm run lint
      - name: Run TypeScript compiler
        run: npm run typecheck
